### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by Rahul-Rajeevan** [Rahul-Rajeevan/b36_col#7]
Navbar to be added

- [x] Navbar created using bootstrap
- [x] Navbar is responsive
- [x] Logo image optimisation done
![image](https://github.com/Rahul-Rajeevan/b36_col/assets/101565872/d47a7f6e-bf96-4644-ab25-b7336b0cae8c)

**Comment by abhigupta3985** [comment]
@Rahul-Rajeevan creating for the optimised image

**Comment by abhigupta3985** [comment]
@Rahul-Rajeevan final product looks like this
